apiVersion: apps/v1
kind: Deployment
metadata:
  name: gokteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gokteto
  template:
    metadata:
      labels:
        app: gokteto
    spec:
      containers:
      - image: okteto.dev/gokteto:latest
        name: gokteto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e5aa6003-4e3c-472d-a150-ca250dd86ef1"
        - name: Vless_Path
          value: "/fgh76wrgjyu"
        - name: Vmess_UUID
          value: "e5aa6003-4e3c-472d-a150-ca250dd86ef1"
        - name: Vmess_Path
          value: "/fdbjui756ehtd"
        - name: Share_Path
          value: "/v2link"
